import { redirect } from 'next/navigation'
import type { NextRequest } from 'next/server'
import { buildAuthUrl } from '@/lib/google-oauth'

export async function GET(request: NextRequest): Promise<Response> {
  const state = request.nextUrl.searchParams.get('state')

  if (!state || state.trim() === '') {
    return new Response('Missing or empty state parameter', { status: 400 })
  }

  // State is generated by the plugin and verified on return — no server storage needed.
  const authUrl = buildAuthUrl(state)

  // redirect() is called outside any try/catch — it throws NEXT_REDIRECT internally.
  redirect(authUrl)
}
